Layout/EndOfLine:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false