Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false